### ISSUE TITLE
Why must width and height be non-zero?

### ISSUE THREAD

**Issue by yoanlcq** [kornelski/imgref#10]
Currently, width and height are not allowed to be zero. In a way, this makes sense, but IMHO it is surprising and impractical.

- AFAIK this isn't mentioned in the documentation, so this is something that might bite at runtime. In any case, if in the end we decide to preserve the current behavior, then it would be nice to provide a rationale in the docs;
- It is not an error for a `Vec` or slice to be empty; In fact this is true of all collections that I know of, and it's quite convenient. Images are "different" because there's no such thing as a 0x0 image; However, there is such a thing as an empty 2D container; For instance...
- I was building a font atlas by rasterizing each ASCII character I was interested in via FreeType into individual bitmaps, then copying the bitmaps into the atlas.  
I decided to change my API so that it returns glyph bitmaps as `ImgVec`s for convenience, but suddenly I get a panic; turns out, the ' ' (space) character effectively yields a 0x0 bitmap.
  My issue is that it is was actually fine, and the code should have kept running as normal. Now I have to check that the height is non-zero every time, and my API now returns `Option<ImgVec<...>>` instead of just `ImgVec<...>`, introducing some noise and branching (but these are nitpicks).  
Of course the issue was not hard to find and it's not going to show up anytime soon. The point is that my code worked fine until I brought `imgref` in... x)

This kind of decision is inherently opinionated and I don't wish to enforce my point of view. It might also be interesting to see what's the stance of similar crates on the matter. :)

**Comment by kornelski** [comment]
OK, removing the restriction on width/height wasn't too hard. I've left requirement for `stride` to be non-0, because `buf.chunks(0)` makes no sense.

**Comment by yoanlcq** [comment]
Thanks, and good point ! At first sight I would have thought it would be OK for stride to be zero, but indeed it's not. Infinite loops are no fun :)
