### ISSUE TITLE
Why does index/index_mut require Pixel to implement Copy

### ISSUE THREAD

**Issue by MikeeyBikeey** [kornelski/imgref#12]
The following code does not compile because `String` does not implement `Copy`:
```rust
fn main() {
    let vec = imgref::ImgVec::new(vec!["world!`".to_string()], 1, 1);
    println!("Hello, {}", vec[(0usize, 0usize)]);
}
```
If you look at `imgref/ops.rs` it requires `Pixel` to implement `Copy`.
Why is `Copy` required?

**Comment by kornelski** [comment]
This library is written with images in mind, and I haven't seen an actual pixel definition that isn't copyable. I hope this catches mistakes.

**Comment by MikeeyBikeey** [comment]
My bad, I was treating `ImgVec` like a 2d vector.
Thanks for the clarification.
