### ISSUE TITLE
rayon

### ISSUE THREAD

**Issue by owenthewizard** [kornelski/imgref#18]
Would it be possible to add rayon support? Right now `par_bridge` can't be used because the iterators aren't `Send`.

**Comment by kornelski** [comment]
You should be able to use `.rows()` iterator. Splitting parallelism per pixel is going to have prohibitively large overhead.

**Comment by owenthewizard** [comment]
Big brain; thanks. 😣

**Comment by LoganDark** [comment]
> You should be able to use `.rows()` iterator. Splitting parallelism per pixel is going to have prohibitively large overhead.

Worked for my path tracer. Rayon is designed to split extremely small workloads.
