### ISSUE TITLE
please consider relicensing this project - use of CC0 for source code is now discouraged

### ISSUE THREAD

**Issue by decathorpe** [kornelski/imgref#19]
The legal status / acceptance of the CC0-1.0 license has recently changed. It is now considered to not be a "good" license for Open Source code due to the lack of an explicit patent waiver.

The application for CC0-1.0 to become an OSI-approved license was withdrawn after receiving criticism, and it is now officially [no longer considered an acceptable license for source code](https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/message/RRYM3CLYJYW64VSQIXY6IF3TCDZGS6LM/) for projects that are packaged for Fedora Linux.

Historically, many other projects have followed the Fedora Project's lead on issues like this, so I expect CC0-1.0 to soon lose its status as an acceptable FOSS license across the ecosystem. For more background, there's an [article](https://www.theregister.com/2022/07/25/fedora_sours_on_creative_commons/) on The Register.

---

EDIT: Alternatives to CC0-1.0 might be the Unlicense (both OSI-approved and FSF-libre, also a Public Domain dedication, similar to CC0-1.0), MIT-0 (OSI-approved, but not FSF-libre), or 0BSD (OSI-approved, but not FSF-libre).

**Comment by kornelski** [comment]
I've added Apache-2.0, so you can have all my 2d array patents :)
